### PR TITLE
Fixing "npm search <packagename>" by changing order of route handling for /-/all

### PR DESCRIPTION
**Pull request by iambrandonn**
...:version

### CODE REVIEW

**Comment by bajtos** [comment]
Hi @iambrandonn, thank you for submitting a pull request.

First of all, please rewrite the commit message to follow the common [50/72 format](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html), i.e.
- First line is 50 characters or less and summarizes the commit
- Then a blank line
- Remaining text should be wrapped at 72 characters and provide longer/additional information.

Also note that we use past tense in commit messages (as opposed to what is used by other git projects).

Example:

```
Fixed "npm search <packagename>"`

Moved the registration of /-/all routes higher so that the are
not handled by /:name/:version
```

Secondly, could you please add a simple unit-test for this change? Take a look at [reggie npm server publishes a package that does not exist yet](https://github.com/mbrevoort/node-reggie/blob/master/test/npm-protocol.js). Your test can be similar: upload a package, run `npm search <packagename>` and check that a correct output was printed to stdout.

**Comment by iambrandonn** [comment]
Let me know if anything else needs to be changed.  Thanks!

**Comment by bajtos** [comment]
Thanks for the updated version, the patch is almost ready for merge. Please fix the two small issues I pointed out in the comments above and squash the changes into a single commit.

**Comment by iambrandonn** [comment]
I just tried to do the squash.  If it doesn't look right let me know.

**Comment by bajtos** [comment]
Landed as 82e99461b and released in v0.1.4.

There was a trailing space at the end of one line and the test file was missing EOL at EOF, I have amended your commit to fix both issues.

Thank you for your contribution!

**Pull request closed without merging**
